# 摄像头状态
CAMERA_OFFLINE = 0
CAMERA_READY = 1
CAMERA_WORKING = 2
CAMERA_UNKNOWN = -1

# HTTP状态
STATUS_OK = 200
STATUS_ERROR = 422 

# 展示设备状态
PREVIEW_OFFLINE = 0
PREVIEW_READY = 1
PREVIEW_WORKING = 2
PREVIEW_UNKNOWN = -1

# 识别服务状态
INDENTIFY_SERVER_OFFLINE = 0
INDENTIFY_SERVER_READY = 1
INDENTIFY_SERVER_WORKING = 2
INDENTIFY_SERVER_UNKNOWN = -1

# 识别状态
INDENTIFY_NONE = 0
INDENTIFY_EXIST = 1
INDENTIFY_MOVING = 2
INDENTIFY_UNKNOWN = -1

# 加工状态
PROCESS_OFFLINE = 0
PROCESS_READY = 1
PROCESS_WORKING = 2
PROCESS_UNKNOWN = -1